// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCS.EntityFramework;

namespace DataCollect.EntityFramework.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20220419054208_v1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataCollect.Core.Entities.Mqtt.CollectPlcData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ComponentProperty")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ComponentPropertyType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DeviceNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("IType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Message")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpcValue")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CollectPlcData");
                });

            modelBuilder.Entity("DataCollect.Core.Entities.Mqtt.MqttConnect", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HeartContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHeartCheck")
                        .HasColumnType("bit");

                    b.Property<bool>("Ispassword")
                        .HasColumnType("bit");

                    b.Property<string>("SubscribeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creatTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("createMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("deleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("finishMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("finishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("finisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("objectStatus")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("updater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("workStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MqttConnect");

                    b.HasData(
                        new
                        {
                            Id = "9a1e30880eaf4ceabf22eed19cabe754",
                            IsHeartCheck = false,
                            Ispassword = false,
                            SubscribeName = "Kengic",
                            UserName = "Kengic",
                            creatTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            deleteFlag = false,
                            finishTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            objectStatus = 0,
                            password = "Kengic@123",
                            port = "1003",
                            updateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            workStatus = 0
                        });
                });

            modelBuilder.Entity("DataCollect.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creatTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("createMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("deleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("finishMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("finishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("finisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("objectStatus")
                        .HasColumnType("int");

                    b.Property<string>("standby1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standby5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("updater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("workStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemConfiguration");
                });

            modelBuilder.Entity("DataCollect.Core.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Name = "超级管理员",
                            Remark = "拥有所有权限"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Name = "测试用户",
                            Remark = "只有测试权限"
                        });
                });

            modelBuilder.Entity("DataCollect.Core.RoleSecurity", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "SecurityId");

                    b.HasIndex("SecurityId");

                    b.ToTable("RoleSecurity");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            SecurityId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            SecurityId = 21
                        });
                });

            modelBuilder.Entity("DataCollect.Core.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Security");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.profile.self",
                            UniqueName = "user.service.profile.self"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.profile",
                            UniqueName = "user.service.profile"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.list",
                            UniqueName = "user.service.list"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.modify.self",
                            UniqueName = "user.service.modify.self"
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.modify",
                            UniqueName = "user.service.modify"
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.delete",
                            UniqueName = "user.service.delete"
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.add",
                            UniqueName = "user.service.add"
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.change.password",
                            UniqueName = "user.service.change.password"
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.roles.self",
                            UniqueName = "user.service.roles.self"
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.roles",
                            UniqueName = "user.service.roles"
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.securities.self",
                            UniqueName = "user.service.securities.self"
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "user.service.securities",
                            UniqueName = "user.service.securities"
                        },
                        new
                        {
                            Id = 13,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "role.service.list",
                            UniqueName = "role.service.list"
                        },
                        new
                        {
                            Id = 14,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "role.service.add",
                            UniqueName = "role.service.add"
                        },
                        new
                        {
                            Id = 15,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "role.service.modify",
                            UniqueName = "role.service.modify"
                        },
                        new
                        {
                            Id = 16,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "role.service.delete",
                            UniqueName = "role.service.delete"
                        },
                        new
                        {
                            Id = 17,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "role.service.give",
                            UniqueName = "role.service.give"
                        },
                        new
                        {
                            Id = 18,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "security.service.list",
                            UniqueName = "security.service.list"
                        },
                        new
                        {
                            Id = 19,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "security.service.give",
                            UniqueName = "security.service.give"
                        },
                        new
                        {
                            Id = 20,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "security.service.refresh",
                            UniqueName = "security.service.refresh"
                        },
                        new
                        {
                            Id = 21,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Remark = "security.service.all",
                            UniqueName = "security.service.all"
                        });
                });

            modelBuilder.Entity("DataCollect.Core.SystemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SystemData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 15, 30, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Name = "男",
                            Remark = "男",
                            Sequence = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 15, 30, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Name = "女",
                            Remark = "女",
                            Sequence = 1
                        });
                });

            modelBuilder.Entity("DataCollect.Core.SystemDataCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("HigherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HigherId");

                    b.ToTable("SystemDataCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 22, 15, 30, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            IsDeleted = false,
                            Name = "性别",
                            Remark = "性别",
                            Sequence = 0
                        });
                });

            modelBuilder.Entity("DataCollect.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Photo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("SigninedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "admin",
                            CreatedTime = new DateTimeOffset(new DateTime(2020, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Enabled = true,
                            Gender = 0,
                            IsDeleted = false,
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            SigninedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DataCollect.Core.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("DataCollect.Core.RoleSecurity", b =>
                {
                    b.HasOne("DataCollect.Core.Role", "Role")
                        .WithMany("RoleSecurities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCollect.Core.Security", "Security")
                        .WithMany("RoleSecurities")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("DataCollect.Core.SystemData", b =>
                {
                    b.HasOne("DataCollect.Core.SystemDataCategory", "Category")
                        .WithMany("Data")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataCollect.Core.SystemDataCategory", b =>
                {
                    b.HasOne("DataCollect.Core.SystemDataCategory", "Higher")
                        .WithMany("Sublevels")
                        .HasForeignKey("HigherId");

                    b.Navigation("Higher");
                });

            modelBuilder.Entity("DataCollect.Core.UserRole", b =>
                {
                    b.HasOne("DataCollect.Core.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCollect.Core.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataCollect.Core.Role", b =>
                {
                    b.Navigation("RoleSecurities");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DataCollect.Core.Security", b =>
                {
                    b.Navigation("RoleSecurities");
                });

            modelBuilder.Entity("DataCollect.Core.SystemDataCategory", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("Sublevels");
                });

            modelBuilder.Entity("DataCollect.Core.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
